name: Feature Request
description: A new feature to be added to the project
title: "feat: "
labels: [feature]
assignees:
  - thecodexhub
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe what you are looking to add. The more business/user context the better.
      placeholder: "Provide a description of the feature."
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: The list of requirements that need to be met in order to consider the issue to be completed. Please be as explicit as possible.
      value: |
        - [ ] All CI/CD checks are passing.
        - [ ] There is no drop in the test coverage percentage.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, including links/screenshots/video recordings/etc about the problem here.
      placeholder: "Provide context here."
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/thecodexhub/typethis/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
